In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [3]:
print("1st element:", x[0])
print("2nd element:", x[1])
print("3rd element:", x[2])

1st element: 1
2nd element: 2
3rd element: 3


In [4]:
print("1st element:", x[-5])
print("2nd element:", x[-4])
print("3rd element:", x[-1])

1st element: 1
2nd element: 2
3rd element: 5


## Modify

In [5]:
x[4] = 20
print(x)

[ 1  2  3  4 20]


In [6]:
X = np.arange(1, 10).reshape(3,3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# note the comma notation instead of the x[0][0]
print("Element at (0,0):", X[0, 0])
print("Element at (0,1):", X[0, 1])
print("Element at (0,2):", X[0, 2])

Element at (0,0): 1
Element at (0,1): 2
Element at (0,2): 3


In [9]:
X[0,0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Delete

In [10]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [11]:
# delete from x, a list of indices
x = np.delete(x, [0, 4])
print(x)

[2 3 4]


In [12]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# axis=0, rows, axis=1, columns
W = np.delete(Y, 0, axis=0)
print(W)

[[4 5 6]
 [7 8 9]]


In [16]:
V = np.delete(Y, [0,2], axis=1)
print(V)

[[2]
 [5]
 [8]]


In [17]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [19]:
x = np.append(x, 6)
print(x)

[1 2 3 4 5 6]


In [20]:
x = np.append(x, [7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [21]:
Y = np.arange(1,10).reshape(3,3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
W = np.append(Y, [[10, 11, 12]], axis=0)
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print(V)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


## Insert

In [28]:
# insert before the given index 
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [29]:
x = np.insert(x, 2, [3,4])
print(x)

[1 2 3 4 5 6 7]


In [30]:
Y = np.array([[1,2,3], [7,8,9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [31]:
Y = np.insert(Y, 1, [4,5,6], axis=0)
print(Y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Stacking (horizontally or vertically)

NumPy also allows us to stack ndarrays on top of each other, or to stack them side by side. The stacking is done using either the np.vstack() function for vertical stacking, or the np.hstack() function for horizontal stacking. It is important to note that in order to stack ndarrays, the shape of the ndarrays must match. Let's see some examples:

In [33]:
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])

print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]
