In [ ]:
# Numpy v Python Stock List 

A quick test to compare the runtime of numpy v Python stock calculations

import time
import numpy as np

In [2]:
x = np.random.random(100000000)

In [16]:
start = time.time()
sum(x) / len(x)
print(time.time() - start)

8.02625584602356


In [17]:
start = time.time() 
np.mean(x)
print(time.time() - start)

0.053241729736328125


In [ ]:
## Creating NumpPy ndarrays

In [18]:
x = np.array([1, 2, 3, 4, 5])

In [19]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
x.dtype

dtype('int64')

In [21]:
x.shape

(5,)

In [25]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Size (rows by col)
Y.shape

In [27]:
Y.size

12

In [ ]:
# rank as the number of dimensions of any array 

In [28]:
x = np.array(["Hello", "World"])
print(x)

['Hello' 'World']


In [29]:
print("shape:", x.shape)
print("type:", type(x))
print("dtype:", x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype: <U5


In [ ]:
# if you create with a mixed type (int and string), np with coerce into a single type
mixed = np.array([1, 2, "World"])
print(x)
print("shape:", mixed.shape)
print("type:", type(mixed))
print("dtype:", mixed.dtype)

In [30]:
# create mixed list of int and floats, np will upcast all to floats 
x = np.array([1,2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [31]:
# but can also specify the dtype
# can be useful when you don't want to leave it to chance 
# or when you want to save memory by using less intensive types
# create mixed list of int and floats, np will upcast all to floats 
x = np.array([1,2.5, 4], dtype=np.int64)
print(x)
print(x.dtype)

[1 2 4]
int64


In [32]:
# saving an array to a file to be read later or to be used by another program
np.save("my_array", x)

In [33]:
# loading an array that has been saved 
y = np.load("my_array.npy")
print(x)
print(y)

[1 2 4]
[1 2 4]


## Using built-in function to create ndarrays

In [40]:
# np.zeros(shape, dtype) with a shape, creates ndarray of zeros
X = np.zeros((3, 4))
print(X)
Y = np.zeros((3, 1, 1))
print(Y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0.]]

 [[0.]]

 [[0.]]]


In [41]:
# shape of array and constant to fill in
X = np.full((4,3), 5)
print(X)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [42]:
# identity matrix, square 2-d arary with 1 along diagonal
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
# diag 
X = np.diag([10, 20, 30, 40, 50])
print(X)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [45]:
# start stop and step arg

# one arg specified, stop exclusive
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
# two args, start and stop
x = np.arange(4, 10)
print(x)

[4 5 6 7 8 9]


In [50]:
# three args
x = np.arange(1, 30, 3)
print(x)

[ 1  4  7 10 13 16 19 22 25 28]


In [51]:
# don't use arange for non-integer steps 
# instead use np.linspace()
# start and stop inclusive
# n number

x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [52]:
# exclusive end poitn with endpoint=False 
x = np.linspace(0, 25, 10, endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [53]:
# reshape 1rank arrays into new shapes 
# must be compatible in terms of total elements 
x = np.arange(20)
print(x)
x = np.reshape(x, (4,5))
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [54]:
x = np.reshape(x, (10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [56]:
#some np functions can be applied as methods which allows us to chain them together 
# don't need to pass in array to reshape()
Y = np.arange(20).reshape((10,2))
print(Y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [57]:
X = np.linspace(0, 50, 10, endpoint=False).reshape(5,2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


# numpy arrays with random numbers


In [58]:
# shape
X = np.random.random((3, 3))
print(X)

[[0.93965265 0.12422212 0.14620309]
 [0.93216947 0.86332794 0.16247643]
 [0.28193126 0.07546818 0.8700877 ]]


In [59]:
# low inclusive, high exclusive and shape
X = np.random.randint(4, 15, (3, 2))
print(X)

[[ 8  6]
 [11 12]
 [ 7  7]]


In [62]:
# random matrices that satisfied certain properties (drawn from distributions)
# mean, stdev, shape/size
X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

[[ 0.11747061  0.13947687  0.04024399 ...  0.18591062 -0.07243097
  -0.02419323]
 [ 0.13379755  0.0749923   0.03915377 ...  0.05271656 -0.07543192
  -0.20464267]
 [-0.06990893 -0.08003395  0.04745765 ... -0.06928837 -0.13693194
   0.0357747 ]
 ...
 [-0.08521735  0.00458432  0.08189484 ...  0.05515777  0.25992655
   0.13037761]
 [ 0.02680711 -0.00253082 -0.05647009 ... -0.00486342 -0.13534928
   0.04914254]
 [ 0.15380635  0.07447332  0.06641074 ... -0.03006886  0.04623457
   0.01439776]]


In [63]:
print("mean:", X.mean())
print("std:", X.std())
print("max:", X.max())
print("min:", X.min())
print("# positive:", (X > 0).sum())
print("# negative:", (X < 0).sum())

mean: -0.00010928102579622314
std: 0.10007909325485556
max: 0.4924976082514064
min: -0.4978669321024298
# positive: 499188
# negative: 500812
